config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  resources :books
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # alias_action :create, :read, :update, :destroy, to: :crud

    # user ||= AdminUser.new # guest user (not logged in)
    # if user.present?
    #   if user.admin_role.name == 'superadmin'
    #     can :manage, :all
    #   else
    #     can :read, :all
    #     # can :read, AdminUser
    #     # can :read, ActiveAdmin::Page, name: "Dashboard", namespace_name: "admin"
    #     # can :update, AdminUser
    #     # can :manage, AdminUser
    #     # can :manage, Book
    #     # can :crud, Book
    #     # cannot [:update, :destroy], Book
    #   end
    # end
  end
end

app/models/admin_role.rb
class AdminRole < ApplicationRecord
  has_many :admin_users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  belongs_to :admin_role
end

app/models/admins_authorization.rb
class AdminsAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    case subject
    when normalized(subject)
      action == :update || action == :destroy ? user.admin_role.name == 'superadmin' : true
    else
      true
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, required: false
  default_scope -> { order(created_at: :asc) }

  after_create :log_book_details

  def log_book_details
    LogJob.perform_later(self)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable , :rememberable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable
  has_many :books

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
  #   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :phone, :email, :password, :password_confirmation, :current_password)}
  # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, except: :index

  def index
    @books = Book.includes(:user)
    # @books = Book.joins(:user).where("books.author = ?", "LogBookDetailsAuthor")
    # @books = Book.eager_load(:user)
    # @books = Book.all
    authorize @books
  end

  def show
    authorize @book
  end

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = current_user.books.new(book_params)
    authorize @book
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    authorize @book
  end

  def update
    authorize @book
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    authorize @book
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :description, :author)
    end

    def set_book
      @book = Book.find(params[:id])
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: false

class HomeController < ApplicationController

  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    # super
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_session_path
    else
      render :new
    end
  end

  def update
    # super
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/books/showbooks.html.haml
%table.table
  %thead.heading-section
    %tr
      %th{:scope => "col"} Title
      %th{:scope => "col"} Description
      %th{:scope => "col"} Author
  %tbody.table-background
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.description
        %td= book.author

app/views/books/_book.html.haml
- @books.each do |book|
  %tr
    %td= book.title
    %td= book.description
    %td= book.author
    %td= link_to "Show", book_path(book), :class => "link-color"
    - if policy(book).edit?
      %td= link_to "Edit", edit_book_path(book), :class => "link-color"
    - if policy(book).destroy?
      %td= link_to "Delete", book_path(book), method: :delete, data: { confirm: "Are you sure?" }, :class => "link-color"

app/views/books/_form.html.haml
= bootstrap_form_with model: @book, local: true do |form|
  %div
    = form.text_field :title
  %div
    = form.text_area :description
    %br/
  %div
    = form.text_area :author
    %br/
  %div
    = form.submit t('books.form.submit')

app/views/books/edit.html.haml
%br/
%h3 Edit Book
= render 'form'
%br/
= link_to "Back", books_path, :class => "btn btn-light"

app/views/books/index.html.haml
%br/
- if policy(Book).new?
  = link_to "New", new_book_path, :class => "link-color btn btn-light"
%br/
%table.table
  %thead.heading-section
    %tr
      %th{:scope => "col"} Title
      %th{:scope => "col"} Description
      %th{:scope => "col"} Author
      %th{:scope => "col"}
      %th{:scope => "col"} Action
      %th{:scope => "col"}
  %tbody.table-background
    = render partial: 'books/book', collection: @books, cached: true

app/views/books/new.html.haml
%br/
%h3 New Book
= render 'form'
%br/
= link_to "Back", books_path, :class => "btn btn-light"

app/views/books/show.html.haml
%br/
%h3= @book.title
%p= @book.description
%p= @book.author
= link_to "Back", books_path, :class => "btn btn-light"
%br/

app/views/home/index.html.haml
%center
  %h1= t '.welcome'
%h1
  = link_to "Books", books_path

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"}= t '.library'
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %form.form-inline.my-2.my-lg-0{:action => "/search"}
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-primary.my-2.my-sm-0{:type => "submit"} Search
  %ul.navbar-nav.mr-auto
    %li.nav-item.active
      - if user_signed_in?
        = link_to "Edit Registration", edit_user_registration_path, :class => 'navbar-brand'
        = link_to "LogOut", destroy_user_session_path, method: :delete, :class => 'navbar-brand'
        = link_to current_user.email, :class => 'navbar-brand'
      - else
        = link_to "SignUp", new_user_registration_path, :class => 'navbar-brand'
        = link_to "LogIn", new_user_session_path, :class => 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LibrarySystem
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container.my-3
      = yield